var languages = {
    en: {
        _LanguageName: 'English',
        userName: 'Username',
        userPassword: 'Password',
        error: 'Error:',
        login: 'Login',
        rememberLogin: 'Remember my login',
        linkPassword: 'Password forgotten',
        oldPassword: 'Current password',
        newPassword: 'New password',
        confirmPassword: 'Confirm new password',
        passwordExpiredMsg: 'Your password has expired please provide a new password',
        changePassword: 'Change',
        pwdToShort: 'to short, minimum length is {{minlength}}',
        pwdToSimple1: 'to simple, please use a combination of letters and numbers',
        pwdToSimple2: 'to simple, please use a combination of letters (small and caps), numbers and at least one special character',
        pwdOldEqNew: 'new cannot be the same as the current password',
        securityCode: 'Security code',
        securityCodeText: 'The security code has been send to you using email, SMS or mobile phone call',
        pwdResetErrorToShort: 'Password is to short',
        pwdResetErrorToSimple: 'Password is to simple',
        pwdResetErrorRepeated: 'Password is repeated',
        pwdResetErrorInvalidOld: 'Password has been used before',
        pwdResetErrorInvalidCode: 'Password security code is not valid',
        pwdResetErrorError: 'Password could not be reset, error is unknown, please cnntact support',
        sendSecurityCode: 'send',
        secSendEmail: 'Email',
        secSendSMS: 'SMS',
        secSendPhone: 'Phone',
        errUnknownUser: 'Unknown user',
        errInvalidUser: 'Invalid user',
        enterUserNameFirst: 'Please specify your user name first',
        clickToSetNewPwd: 'Click here to set a new password',
        passwordRequestedMsg: 'You have requested a new password',
        passwordReset: 'Your password has been reset',
        errUnkownUser: 'Unknown user specification',
        twoFactorRequiredMsg: 'A second validation is required before the login is completed',
        pwdResetErrorTwoFactorFailed: 'Invalid security code specified!',
    },
    nl: {
        _LanguageName: 'Nederlands',
        userName: 'Gebruikersnaam',
        userPassword: 'Wachtwoord',
        error: 'Fout:',
        login: 'Aanmelden',
        rememberLogin: 'Gebruikersnaam onthouden',
        linkPassword: 'Wachtwoord vergeten',
        oldPassword: 'Huidig wachtwoord',
        newPassword: 'Nieuw wachtwoord',
        confirmPassword: 'Bevestig nieuw wachtwoord',
        passwordExpiredMsg: 'Uw huidige wachtwoord is verlopen, specificeer een nieuw wachtwoord',
        changePassword: 'Wijzig',
        pwdToShort: 'wachtwoord te kort, minimale lengte is {{minlength}}',
        pwdToSimple1: 'te eenvoudig, gebruik een combinatie van letters en cijfers',
        pwdToSimple2: 'te eenvoudig, gebruik een combinatie van letters (klein en groot), cijfers en minimaal 1 special teken',
        pwdOldEqNew: 'huidige en nieuwe wachtwoord mogen niet gelijk zijn',
        securityCode: 'Beveiligings code',
        securityCodeText: 'De beveiligingscode is naar u toegestuurd via email, SMS of telefoon',
        pwdResetErrorToShort: 'Wachtwoord is te kort',
        pwdResetErrorToSimple: 'Wachtwoord is te simpel',
        pwdResetErrorRepeated: 'Wachtwoord is herhaald',
        pwdResetErrorInvalidOld: 'Wachtwoord is eerder gebruikt',
        pwdResetErrorInvalidCode: 'Wachtwoord beveiligings code is niet geldig',
        pwdResetErrorError: 'Wachtwoord kan niet worde ingesteld door een onbekende fout, neem contact op met de support afdeling',
        sendSecurityCode: 'stuur',
        secSendEmail: 'Email',
        secSendSMS: 'SMS',
        secSendPhone: 'Mobiel',
        errUnknownUser: 'Onbekende gebruiker',
        errInvalidUser: 'Ongeldige gebruiker',
        enterUserNameFirst: 'Specificeer eerst uw gebruikersnaam',
        clickToSetNewPwd: 'Klik hier om een nieuw wachtwoord in te stellen',
        passwordRequestedMsg: 'U heeft een nieuw wachtwoord aangevraagd',
        passwordReset: 'Uw wachtwoord is opnieuw ingesteld',
        errUnkownUser: 'Onbekende gebruikersnaam',
        twoFactorRequiredMsg: 'Er is een tweede validatie nodig om de login af te ronden',
        pwdResetErrorTwoFactorFailed: 'Ongeldige beveiligingscode opgegeven',
    },
    de: {
        _LanguageName: 'Deutsch',
        userName: 'Nutzername',
        userPassword: 'Passwort',
        error: 'Fehler:',
        login: 'Anmelden',
        rememberLogin: 'Speichere mich',
        linkPassword: 'Passwort vergessen',
        oldPassword: 'Current password',
        newPassword: 'New password',
        confirmPassword: 'Confirm new password',
        passwordExpiredMsg: 'Your password has expired please provide a new password',
        changePassword: 'Change',
        pwdToShort: 'password to short, minimum length is {{minlength}}',
        pwdToSimple1: 'to simple, please use a combination of letters and numbers',
        pwdToSimple2: 'to simple, please use a combination of letters (small and caps) and numbers and at least one special character',
        pwdOldEqNew: 'new cannot be the same as the current password',
        securityCode: 'Security code',
        securityCodeText: 'The security code has been send to you using email, SMS or mobile phone call',
        pwdResetErrorToShort: 'Password is to short',
        pwdResetErrorToSimple: 'Password is to simple',
        pwdResetErrorRepeated: 'Password is repeated',
        pwdResetErrorInvalidOld: 'Password has been used before',
        pwdResetErrorInvalidCode: 'Password security code is not valid',
        pwdResetErrorError: 'Password could not be reset, error is unknown, please cnntact support',
        sendSecurityCode: 'send',
        secSendEmail: 'Email',
        secSendSMS: 'SMS',
        secSendPhone: 'Mobiel',
        errUnknownUser: 'Unknown user',
        errInvalidUser: 'Invalid user',
        enterUserNameFirst: 'Please specify your user name first',
        clickToSetNewPwd: 'Click here to set a new password',
        passwordRequestedMsg: 'You have requested a new password',
        passwordReset: 'Your password has been reset',
        errUnkownUser: 'Unknown user specification',
        twoFactorRequiredMsg: 'A second validation is required before the login is completed',
        pwdResetErrorTwoFactorFailed: 'Invalid security code specified!',
    }
};
